version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: testUnit
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Express Backend
  app:
    build: .
    container_name: express_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://admin:Aa123456@db:5432/testUnit"
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/app               # mount source code
      - /app/node_modules    # ignore host node_modules
    command: npm start       # ใช้ start ปกติ

  # pgAdmin GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
