CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  entity_type VARCHAR(100) NOT NULL,
  entity_name VARCHAR(255) NOT NULL,
  tax_id VARCHAR(255) NOT NULL UNIQUE,
  address_number VARCHAR(100) NOT NULL,
  village_no VARCHAR(20),
  building VARCHAR(255),
  address_soi VARCHAR(255),
  address_road VARCHAR(255) NOT NULL,
  subdistrict VARCHAR(255) NOT NULL,
  district VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  contact_title VARCHAR(50) NOT NULL,
  contact_first_name VARCHAR(100) NOT NULL,
  contact_last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  referral_code VARCHAR(100),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);
